### ISSUE TITLE
How to run mst.cu or mstnew.cu?

### ISSUE THREAD

**Issue by Michael2397** [Dibyadarshan/GPU-Based-Fast-Minimum-Spanning-Tree#1]
In mstnew.cu, there is a function named "weightUpdate", but you never used it, can you tell me how to realize GPU-Based-Fast-Minimum-Spanning-Tree? Thank you

**Comment by omkarprabhu-98** [comment]
mst_new.cu was something we were trying out and not yet functional. 
Usage instructions for GPU-Based-Fast-Minimum-Spanning-Tree are in the readme.
Cheers

**Comment by omkarprabhu-98** [comment]
I hope its resolved
